# ./pnpm-workspace.yaml
packages:
  # root directory
  - "."
  # all packages in subdirs of packages/
  - "package/**"
  # exclude packages that are inside test/ directories
  # - "!**/test/**" # '!' means exclude
